### PR TITLE
Fix TypeError when working with nested maps [JIRA: CLIENTS-417]

### LINKED ISSUE #401: Updating nested maps raises TypeError [JIRA: CLIENTS-349]
```
In [8]: from riak import RiakClient
In [9]: c = RiakClient()
In [14]: b = c.bucket_type('maps').bucket('wow')                                                        
In [15]: m = b.get('key')
In [16]: m.maps['such'].counters['very'].increment(0)
In [17]: m.to_op()
Out[17]: [('update', ('such', 'map'), None)]
In [18]: m.update()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-4208fc8f76fe> in <module>()
----> 1 m.update()

/lib/python3.4/site-packages/riak/datatypes/datatype.py in update(self, **params)
    143 
    144         params.setdefault('return_body', True)
--> 145         self.bucket._client.update_datatype(self, **params)
    146         self.clear()
    147 

/lib/python3.4/site-packages/riak/client/operations.py in update_datatype(self, datatype, w, dw, pw, return_body, timeout, include_context)
    999                                              return_body=return_body,
   1000                                              timeout=timeout,
-> 1001                                              include_context=include_context)
   1002 
   1003     @retryable

/lib/python3.4/site-packages/riak/transports/pbc/transport.py in update_datatype(self, datatype, **options)
    687         self._encode_dt_options(req, options)
    688 
--> 689         self._encode_dt_op(type_name, req, op)
    690 
    691         msg_code, resp = self._request(MSG_CODE_DT_UPDATE_REQ, req,

/lib/python3.4/site-packages/riak/transports/pbc/codec.py in _encode_dt_op(self, dtype, req, op)
    578             self._encode_set_op(req.op, op)
    579         elif dtype == 'map':
--> 580             self._encode_map_op(req.op.map_op, op)
    581         else:
    582             raise TypeError("Cannot send operation on datatype {!r}".

/lib/python3.4/site-packages/riak/transports/pbc/codec.py in _encode_map_op(self, msg, ops)
    605                 update.field.name = str_to_bytes(name)
    606                 update.field.type = ftype
--> 607                 self._encode_map_update(dtype, update, op[2])
    608 
    609     def _encode_map_update(self, dtype, msg, op):

/lib/python3.4/site-packages/riak/transports/pbc/codec.py in _encode_map_update(self, dtype, msg, op)
    614             self._encode_set_op(msg, op)
    615         elif dtype == 'map':
--> 616             self._encode_map_op(msg.map_op, op)
    617         elif dtype == 'register':
    618             # ('assign', some_str)

/lib/python3.4/site-packages/riak/transports/pbc/codec.py in _encode_map_op(self, msg, ops)
    590 
    591     def _encode_map_op(self, msg, ops):
--> 592         for op in ops:
    593             name, dtype = op[1]
    594             ftype = MAP_FIELD_TYPES[dtype]

TypeError: 'NoneType' object is not iterable

In [19]: m.modified
Out[19]: True
```

`modified and to_op()` must be None.

Furthermore, just triggering empty `m.maps['blabla'].counters['blablabla'].value` changes state of `m` to modified. It is a get operation and get operations are idempotent and must not change the state of the underlying object.

### PR DESCRIPTION
**Pull request by nicorevin**
Fixes #401 (CLIENTS-349)

### CODE REVIEW

**Comment by javajolt** [comment]
@nicorevin Could you please add a test case for your change?  That would help me to verify.  Thanks!

**Comment by nicorevin** [comment]
@javajolt I've added. See `riak/tests/test_datatypes.py`

**Comment by javajolt** [comment]
Sorry, I missed it.  Thanks!

**Comment by javajolt** [comment]
:+1: 4dca64c

**Comment by javajolt** [comment]
Looks like `make lint` failed.  I'm guessing this is a newer version of `pep8`.  I'll create a new PR to address that.

**Comment by javajolt** [comment]
@borshop: merge

**Comment by nicorevin** [comment]
By the way, is it ok that `modified` attribute does not correspond with `_updates` and `to_op() is None`?
Even without this PR we have the following picture:
```
In [1]: from riak import RiakClient
In [2]: c = RiakClient()
In [3]: b = c.bucket_type('maps').bucket('wow')
In [4]: m = b.get('key')
In [5]: m.__dict__
Out[5]: 
{'_context': None,
 '_removes': set(),
 '_updates': {},
 '_value': {},
 'bucket': <RiakBucket 'maps'/'wow'>,
 'key': 'key'}

In [6]: m.maps['a']                                                                                                                                                                  
Out[6]: <riak.datatypes.map.Map at 0x7fad9a294c50>
In [7]: m.flags['b']                                                                                                                                                                 
Out[7]: <riak.datatypes.flag.Flag at 0x7fad99be8668>
In [8]: m.registers['c']                                                                                                                                                             
Out[8]: <riak.datatypes.register.Register at 0x7fad99be8278>
In [9]: m.counters['d']                                                                                                                                                              
Out[9]: <riak.datatypes.counter.Counter at 0x7fad99be8630>

In [10]: m._updates
Out[10]: 
{('a', 'map'): <riak.datatypes.map.Map at 0x7fad9a294c50>,
 ('b', 'flag'): <riak.datatypes.flag.Flag at 0x7fad99be8668>,
 ('c', 'register'): <riak.datatypes.register.Register at 0x7fad99be8278>,
 ('d', 'counter'): <riak.datatypes.counter.Counter at 0x7fad99be8630>}

In [11]: m.to_op()
# None

In [12]: m.modified
Out[12]: True

In [13]: m.context
# None
```
Of course if we call `m.update()` we catch `No operation to send` exception.
It means we know we have nothing to commit but we set the `modified` flag to `true` and keep the stack of local changes that will never ever be commited. Why?

**Comment by nicorevin** [comment]
Updated pull request regarding my last comment.

**Comment by nicorevin** [comment]
Hi! Any updates?

**Comment by javajolt** [comment]
Hmmm... Looks like it tried to get merged on April 16th, but I see no successful merge messages.  Looks like our merge tool does not work on other repos.  Let me look at your subsequent changes now, too.

**Comment by nicorevin** [comment]
We've been successfully using this patch for more than half a year.
Any chances for this to be merged into upstream?

**Pull request merged**
