### PR TITLE
Use default Python file encoding during test / release process

### LINKED ISSUE #476: Encoding environment variables [JIRA: CLIENTS-864]
The following environment variables influence the default encoding of the Python interpreter:

```sh
$ declare -x|fgrep -i utf
declare -x LANG="en_US.UTF-8"
declare -x LC_ADDRESS="en_US.UTF-8"
declare -x LC_COLLATE="en_US.UTF-8"
declare -x LC_CTYPE="en_US.UTF-8"
declare -x LC_IDENTIFICATION="en_US.UTF-8"
declare -x LC_MEASUREMENT="en_US.UTF-8"
declare -x LC_MESSAGES="en_US.UTF-8"
declare -x LC_MONETARY="en_US.UTF-8"
declare -x LC_NAME="en_US.UTF-8"
declare -x LC_NUMERIC="en_US.UTF-8"
declare -x LC_PAPER="en_US.UTF-8"
declare -x LC_TELEPHONE="en_US.UTF-8"
declare -x LC_TIME="en_US.UTF-8"
```

These should be unset or set to `C` in the Makefile to "genericize" the encoding environment and simulate a wider range of end-user environments.

Inspired by PR #474

### PR DESCRIPTION
**Pull request by lukebakken**
Unexport vars related to encoding, ensure files are opened with utf-8 when necessary.

Fixes #476 (CLIENTS-864) 
Addresses #474

### CODE REVIEW

**Comment by lukebakken** [comment]
@javajolt this was an interesting issue

**Comment by javajolt** [comment]
@lukebakken I should be able to test this by setting my default lang to something crazy and everything should work, right?

**Comment by lukebakken** [comment]
That's one way, but if you use the `Makefile` targets it will ensure any environment vars that set lang will be unset. That way you'll use whatever the default is for your Python interpreter.

**Comment by lukebakken** [comment]
@javajolt - do you have any set in your env? What is the output of this command?

```sh
declare -x | fgrep -i utf
```

**Comment by javajolt** [comment]
`declare -x LANG="en_US.UTF-8"`

**Comment by lukebakken** [comment]
OK so the `Makefile` will unexport that and Python will use whatever its default is.

**Comment by javajolt** [comment]
Seems to work fine

**Comment by javajolt** [comment]
👍 5e5c550

**Pull request merged**
