### PR TITLE
added head_only parameter for pbc transport

### PR DESCRIPTION
**Pull request by tobixx**
Implements the head only request on pbc protocol. Solves #134 (CLIENTS-776) (CLIENTS-1039) .

### CODE REVIEW

**Comment by tobixx** [comment]
Have to close it due to http protocol errors - some more edges need the additional parameter.
Normal test did not got them because they run on pbc normally.

**Comment by tobixx** [comment]
Was only one edge. Also added support for multiget.

**Comment by lukebakken** [comment]
Thanks!

**Comment by lukebakken** [comment]
Included in #509

**Pull request closed without merging**
