### PR TITLE
DP-6 new API entry point methods #398 [JIRA: CLIENTS-201]

### PR DESCRIPTION
**Pull request by hmmr**
* client.get_api_entry_point(bucket, key, proto)
* client.get_api_entry_points_map(proto)

### CODE REVIEW

**Comment by javajolt** [comment]
@hmmr Thanks for the PR.

I'm starting to take a look at what you have and we have a few issues before we can consider merging.

First off, it looks like there are a couple of dependent PRs which first need to be approved:
- https://github.com/basho/riak_pb/pull/106
- https://github.com/basho/riak_kv/pull/1084

Once they are in, then we'd need some tests added to this PR as well as `pep8` and `pyflakes` run to clean up the formatting to pass our lint test.  You can verify this by running `make lint` from the `buildbot` directory.

Also I see you are specifying the protocol in your request.  Guessing you are wanting to separate that from the actual request transport, i.e., being able to request the PB endpoints via HTTP and vice-a-versa, right?

**Comment by hmmr** [comment]
@javajolt Yes, those two PRs in riak_pb and _kv should go first, that's correct.

While this is being done, I'll check for any outstanding lint issues and see to functional tests for the python client.

The protocol makes two appearances in this PR, indeed, it is the protocol *of* the current API calls, and it is also an argument *in* those same calls. The two uses of it are completely orthogonal, that's also correct.

**Comment by hmmr** [comment]
There is a new dependency, https://github.com/basho/riak_api/pull/84.

Provisionally force-pushing to facilitate team work. No functional test yet.

**Comment by javajolt** [comment]
Thanks for the update, @hmmr.

**Comment by mdigan** [comment]
Closing this pull request. We're taking a different approach. John and Mark will be enhancing the coverage plan API, and we'll be adding functionality in the java client to use the new API features, and using all of those in the spark connector.

**Pull request closed without merging**
