### PR TITLE
Avoid dependency on pyOpenSSL when using Python 2.7.9 [JIRA: CLIENTS-408]

### PR DESCRIPTION
**Pull request by alefend**
Many enhancements of the Python 3 ssl module have been backported to Python 2.7.9.
In particular, the class `SSLContext()` is available and could be used instead of relying on the pyOpenSSL module. This would avoid the inclusion of a lot of new dependencies: pyopenssl, cryptography, pyasn1, enum34, pycparser, cffi.

I suggest to change [riak/transports/security.py](https://github.com/basho/riak-python-client/blob/2.2.0/riak/transports/security.py) not to use `six.PY2` to decide whether to use the pyOpenSSL, and instead check for the actual availability of `ssl.SSLContext`.

### CODE REVIEW

**Comment by alefend** [comment]
Another option would be to make those dependencies optional using the [`extras_require` feature of `setuptools`] (https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).

I saw it used for a similar purpose in the [`requests` package] (https://github.com/kennethreitz/requests/blob/master/setup.py).

**Comment by javajolt** [comment]
@alefend How is the 2.7.9 port?  I found that in 3.3 there were missing features found in 3.4, for example.

**Comment by alefend** [comment]
Hi @javajolt, we are currently using the proposed changes in production without issues (but against a Riak server with no security)

**Comment by javajolt** [comment]
@alefend Awesome!  I'll just have to verify everything still works on the various other versions, too.  It looks like the Certificate Revocation Lists are still not working in native Python; something pyOpenSSL did support.  Let me review all the changes you made.

**Comment by Basho-JIRA** [comment]
[~brett] it looks like this can be moved along the Jira board.  Will this be the only thing added in the next Python client release? 

***[posted via JIRA by Derek Somogyi]***

**Comment by Basho-JIRA** [comment]
No I hope to get in [CLIENTS-342|https://bashoeng.atlassian.net/browse/CLIENTS-342], [CLIENTS-417|https://bashoeng.atlassian.net/browse/CLIENTS-417], [CLIENTS-361|https://bashoeng.atlassian.net/browse/CLIENTS-361], [CLIENTS-332|https://bashoeng.atlassian.net/browse/CLIENTS-332] and see if I can fix [CLIENTS-514|https://bashoeng.atlassian.net/browse/CLIENTS-514] 

***[posted via JIRA by Brett Hazen]***

**Comment by Basho-JIRA** [comment]
This went out with the 2.3.0 release: https://github.com/basho/riak-python-client/pull/397 

***[posted via JIRA by Brett Hazen]***

**Pull request merged**
